# Generated by Django 6.0.1 on 2026-02-04 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowOfExecutionModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('process_id', models.CharField(db_index=True, max_length=255)),
                ('parent_foe_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Flow of Execution',
                'verbose_name_plural': 'Flows of Execution',
                'db_table': 'zebra_flows_of_execution',
            },
        ),
        migrations.CreateModel(
            name='ProcessDefinitionModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.IntegerField(default=1)),
                ('data', models.TextField(help_text='JSON serialized ProcessDefinition')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Process Definition',
                'verbose_name_plural': 'Process Definitions',
                'db_table': 'zebra_process_definitions',
            },
        ),
        migrations.CreateModel(
            name='ProcessLockModel',
            fields=[
                ('process_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=255)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Process Lock',
                'verbose_name_plural': 'Process Locks',
                'db_table': 'zebra_process_locks',
            },
        ),
        migrations.CreateModel(
            name='ProcessInstanceModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('definition_id', models.CharField(db_index=True, max_length=255)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('properties', models.TextField(blank=True, default='{}', help_text='JSON serialized properties dict')),
                ('parent_process_id', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Process Instance',
                'verbose_name_plural': 'Process Instances',
                'db_table': 'zebra_process_instances',
                'indexes': [models.Index(fields=['state', 'created_at'], name='zebra_proce_state_2d453c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskInstanceModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('process_id', models.CharField(db_index=True, max_length=255)),
                ('task_definition_id', models.CharField(max_length=255)),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('foe_id', models.CharField(db_index=True, max_length=255)),
                ('properties', models.TextField(blank=True, default='{}', help_text='JSON serialized properties dict')),
                ('result', models.TextField(blank=True, help_text='JSON serialized task result', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if task failed', null=True)),
                ('execution_attempt', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Task Instance',
                'verbose_name_plural': 'Task Instances',
                'db_table': 'zebra_task_instances',
                'indexes': [models.Index(fields=['process_id', 'state'], name='zebra_task__process_c202c0_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(db_index=True, max_length=255)),
                ('goal', models.TextField(help_text="User's goal/request")),
                ('started_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('user_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('output', models.TextField(blank=True, help_text='Workflow output/result', null=True)),
            ],
            options={
                'verbose_name': 'Workflow Run',
                'verbose_name_plural': 'Workflow Runs',
                'db_table': 'zebra_workflow_runs',
                'indexes': [models.Index(fields=['-started_at'], name='zebra_workf_started_181076_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('task_definition_id', models.CharField(max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('execution_order', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output', models.TextField(blank=True, help_text='Task output/result', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if failed', null=True)),
                ('run', models.ForeignKey(db_column='run_id', on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='api.workflowrunmodel')),
            ],
            options={
                'verbose_name': 'Task Execution',
                'verbose_name_plural': 'Task Executions',
                'db_table': 'zebra_task_executions',
                'indexes': [models.Index(fields=['run', 'execution_order'], name='zebra_task__run_id_8217dd_idx')],
            },
        ),
    ]
