# Generated by Django 6.0.1 on 2026-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermThemeModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('theme', models.TextField(help_text='Theme text')),
                ('tokens', models.IntegerField(default=0)),
                ('short_term_refs', models.JSONField(default=list, help_text='List of short-term summary IDs this theme references')),
            ],
            options={
                'verbose_name': 'Long-Term Theme',
                'verbose_name_plural': 'Long-Term Themes',
                'db_table': 'zebra_memory_themes',
                'indexes': [models.Index(fields=['-created_at'], name='zebra_memor_created_750cc5_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemoryEntryModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('goal', models.TextField(help_text="User's goal or request")),
                ('workflow_used', models.CharField(max_length=255)),
                ('result_summary', models.TextField(help_text='Summary of the result')),
                ('tokens', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Memory Entry',
                'verbose_name_plural': 'Memory Entries',
                'db_table': 'zebra_memory_entries',
                'indexes': [models.Index(fields=['-timestamp'], name='zebra_memor_timesta_9a80c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShortTermSummaryModel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('summary', models.TextField(help_text='Compacted summary text')),
                ('tokens', models.IntegerField(default=0)),
                ('entry_count', models.IntegerField(default=0, help_text='Number of entries summarized')),
            ],
            options={
                'verbose_name': 'Short-Term Summary',
                'verbose_name_plural': 'Short-Term Summaries',
                'db_table': 'zebra_memory_summaries',
                'indexes': [models.Index(fields=['-created_at'], name='zebra_memor_created_7cfca9_idx')],
            },
        ),
    ]
