# Generated by Django 6.0.1 on 2026-03-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_replace_memory_with_workflow_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmemorymodel',
            name='user_feedback',
            field=models.TextField(blank=True, default='', help_text='Free-text user feedback for next run'),
        ),
    ]
