# Generated by Django 6.0.1 on 2026-03-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_user_feedback_to_workflow_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowmemorymodel',
            name='run_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Link to the workflow run for post-hoc updates', max_length=255),
        ),
    ]
