# Generated by Django 6.0.1 on 2026-03-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_add_run_id_to_workflow_memory"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowmemorymodel",
            name="model",
            field=models.CharField(
                blank=True, default="", help_text="LLM model used for this run", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="workflowrunmodel",
            name="model",
            field=models.CharField(
                blank=True, default="", help_text="LLM model used for this run", max_length=255
            ),
        ),
    ]
