# Generated by Django 6.0.1 on 2026-04-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_add_cost_and_token_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemStateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("halted", models.BooleanField(default=False)),
                ("halted_at", models.DateTimeField(blank=True, null=True)),
                ("halted_reason", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "System State",
                "db_table": "zebra_system_state",
            },
        ),
    ]
