# Generated by Django 6.0.1 on 2026-04-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_kill_switch_system_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemstatemodel",
            name="setup_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="systemstatemodel",
            name="user_display_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="systemstatemodel",
            name="user_identity_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
