# Generated by Django 6.0.1 on 2026-04-23 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_identity"),
        ("api", "0009_webauthncredential"),
    ]

    operations = []
