# Generated by Django 6.0.1 on 2026-04-27 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_user_id_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValuesProfileModel",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Values Profile",
                "verbose_name_plural": "Values Profiles",
                "db_table": "zebra_values_profiles",
            },
        ),
        migrations.AlterField(
            model_name="webauthncredential",
            name="transports",
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name="ValuesProfileVersionModel",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("version_number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_via", models.CharField(default="wizard", max_length=20)),
                ("core_values_text", models.TextField(blank=True, default="")),
                ("core_values_tags", models.JSONField(default=list)),
                ("ethical_positions_text", models.TextField(blank=True, default="")),
                ("ethical_positions_tags", models.JSONField(default=list)),
                ("priorities_text", models.TextField(blank=True, default="")),
                ("priorities_tags", models.JSONField(default=list)),
                ("deal_breakers_text", models.TextField(blank=True, default="")),
                ("deal_breakers_tags", models.JSONField(default=list)),
                ("tags_extracted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "tags_extraction_model",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.valuesprofilemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Values Profile Version",
                "verbose_name_plural": "Values Profile Versions",
                "db_table": "zebra_values_profile_versions",
            },
        ),
        migrations.AddField(
            model_name="valuesprofilemodel",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.valuesprofileversionmodel",
            ),
        ),
        migrations.CreateModel(
            name="ValuesTagModel",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("core_values", "Core values"),
                            ("ethical_positions", "Ethical positions"),
                            ("priorities", "Priorities"),
                            ("deal_breakers", "Deal-breakers"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("slug", models.CharField(max_length=100)),
                ("label", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("seeded", "Seeded"),
                            ("promoted", "Promoted"),
                            ("candidate", "Candidate"),
                        ],
                        default="candidate",
                        max_length=20,
                    ),
                ),
                ("usage_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Values Tag",
                "verbose_name_plural": "Values Tags",
                "db_table": "zebra_values_tags",
                "indexes": [
                    models.Index(
                        fields=["field", "status"],
                        name="zebra_value_field_5d1f98_idx",
                    ),
                    models.Index(
                        fields=["status", "-usage_count"],
                        name="zebra_value_status_e80175_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("field", "slug"),
                        name="zebra_values_tag_field_slug_unique",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="valuesprofileversionmodel",
            index=models.Index(
                fields=["profile", "-version_number"],
                name="zebra_value_profile_296874_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="valuesprofileversionmodel",
            constraint=models.UniqueConstraint(
                fields=("profile", "version_number"),
                name="zebra_vpv_profile_version_unique",
            ),
        ),
    ]
