# Generated by Django 6.0.4 on 2026-05-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_routine_runs"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeEntryModel",
            fields=[
                ("id", models.CharField(max_length=36, primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("preferences", "Preferences"),
                            ("facts", "Facts"),
                            ("relationships", "Relationships"),
                            ("routines", "Routines"),
                            ("skills", "Skills"),
                            ("history", "History"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("value", models.TextField()),
                ("source", models.CharField(default="human", max_length=50)),
                ("confidence", models.FloatField(default=1.0)),
                ("last_verified", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Knowledge Entry",
                "verbose_name_plural": "Knowledge Entries",
                "db_table": "zebra_knowledge_entries",
                "indexes": [
                    models.Index(fields=["user_id", "category"], name="zebra_know_user_cat_idx")
                ],
            },
        ),
    ]
