# Generated by Django 6.0.4 on 2026-05-08 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_knowledgeentrymodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgeentrymodel",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="knowledgeentrymodel",
            name="time_sensitive",
            field=models.BooleanField(default=False),
        ),
    ]
