# Generated by Django 6.0.4 on 2026-05-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_knowledgeentrymodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="EthicsAuditEntryModel",
            fields=[
                ("id", models.CharField(max_length=36, primary_key=True, serialize=False)),
                ("process_id", models.CharField(db_index=True, max_length=255)),
                ("goal", models.TextField(help_text="First 500 chars of the evaluated goal")),
                ("approved", models.BooleanField(db_index=True)),
                ("overall_reasoning", models.TextField()),
                (
                    "check_type",
                    models.CharField(help_text="'kantian' or 'kantian+values'", max_length=50),
                ),
                ("user_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("evaluated_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Ethics Audit Entry",
                "verbose_name_plural": "Ethics Audit Entries",
                "db_table": "ethics_audit_entry",
                "indexes": [
                    models.Index(fields=["-evaluated_at"], name="ethics_audi_evaluat_e25b12_idx"),
                    models.Index(
                        fields=["approved", "-evaluated_at"],
                        name="ethics_audi_approve_d6fe91_idx",
                    ),
                ],
            },
        ),
    ]
