# Generated by Django 6.0.4 on 2026-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_merge_knowledge_lifecycle_ethics_audit"),
    ]

    operations = [
        migrations.AddField(
            model_name="conceptualmemorymodel",
            name="tier",
            field=models.CharField(
                default="hot", help_text="Compaction tier: hot | warm | cold", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="workflowmemorymodel",
            name="tier",
            field=models.CharField(
                default="hot", help_text="Compaction tier: hot | warm | cold", max_length=10
            ),
        ),
    ]
