# Generated by Django 6.0.4 on 2026-06-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_conceptualmemorymodel_tier_workflowmemorymodel_tier"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustChangeModel",
            fields=[
                ("id", models.CharField(max_length=36, primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(db_index=True)),
                ("domain", models.CharField(db_index=True, max_length=100)),
                ("old_level", models.CharField(max_length=20)),
                ("new_level", models.CharField(max_length=20)),
                ("reason", models.TextField()),
                ("changed_by", models.CharField(max_length=255)),
                ("changed_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Trust Change",
                "verbose_name_plural": "Trust Changes",
                "db_table": "zebra_trust_changes",
                "indexes": [
                    models.Index(
                        fields=["user_id", "domain", "-changed_at"],
                        name="zebra_trust_user_id_ceade8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TrustLevelModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("user_id", models.IntegerField(db_index=True)),
                ("domain", models.CharField(max_length=100)),
                ("level", models.CharField(default="SUPERVISED", max_length=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Trust Level",
                "verbose_name_plural": "Trust Levels",
                "db_table": "zebra_trust_levels",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user_id", "domain"), name="zebra_trust_user_domain_unique"
                    )
                ],
            },
        ),
    ]
