# Generated by Django 6.0.4 on 2026-06-12 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0019_trustchangemodel_trustlevelmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustSuggestionModel",
            fields=[
                ("id", models.CharField(max_length=36, primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(db_index=True)),
                ("domain", models.CharField(max_length=100)),
                ("to_level", models.CharField(max_length=20)),
                ("evidence", models.TextField()),
                ("status", models.CharField(db_index=True, default="pending", max_length=10)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_by", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "Trust Suggestion",
                "verbose_name_plural": "Trust Suggestions",
                "db_table": "zebra_trust_suggestions",
                "indexes": [
                    models.Index(
                        fields=["user_id", "status", "-created_at"],
                        name="zebra_trust_user_id_9891b9_idx",
                    )
                ],
            },
        ),
    ]
