# Generated by Django 6.0.4 on 2026-06-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_trustsuggestionmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustFreedModel",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("initiated_at", models.DateTimeField()),
                ("initiated_by", models.CharField(max_length=255)),
                ("freed", models.BooleanField(default=False)),
                ("freed_at", models.DateTimeField(blank=True, null=True)),
                ("freed_by", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "Trust Freed State",
                "verbose_name_plural": "Trust Freed States",
                "db_table": "zebra_trust_freed",
            },
        ),
    ]
