# Generated by Django 6.0.4 on 2026-09-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0021_trustfreedmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="valuestagmodel",
            name="merged_into",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="valuestagmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("seeded", "Seeded"),
                    ("promoted", "Promoted"),
                    ("candidate", "Candidate"),
                    ("rejected", "Rejected"),
                    ("merged", "Merged"),
                ],
                default="candidate",
                max_length=20,
            ),
        ),
    ]
