# Generated by Django 6.0.4 on 2026-09-26 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0022_values_tag_curation"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrunmodel",
            name="extends_run_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Run this one follows up on (F116)",
                max_length=255,
                null=True,
            ),
        ),
    ]
