# Generated by Django 6.0.4 on 2026-10-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0023_workflow_run_extends"),
    ]

    operations = [
        migrations.AddField(
            model_name="workflowrunmodel",
            name="continuation_comment",
            field=models.TextField(
                blank=True,
                help_text="User's progress comment when continuing a run (F134)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowrunmodel",
            name="continuation_decision",
            field=models.CharField(
                blank=True,
                help_text="same_workflow | existing_workflow | new_workflow (F135)",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="workflowrunmodel",
            name="continuation_rationale",
            field=models.TextField(
                blank=True, help_text="Why the continuation route was chosen (F135)", null=True
            ),
        ),
    ]
