# Generated by Django 6.0.4 on 2026-10-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0024_workflow_run_continuation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knowledgeentrymodel",
            name="category",
            field=models.CharField(
                choices=[
                    ("preferences", "Preferences"),
                    ("facts", "Facts"),
                    ("relationships", "Relationships"),
                    ("routines", "Routines"),
                    ("skills", "Skills"),
                    ("history", "History"),
                    ("world", "World"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
