#!/usr/bin/env bash
# Deploy Zebra to rootless Podman on this host (F117).
#
#   scripts/deploy-podman.sh <tag>        # build localhost/zebra-web:<tag>, promote to :prod
#   scripts/deploy-podman.sh --rollback   # re-promote the previous :prod image
#
# Steps: write prod.env from CI variables -> build image -> install Quadlet units ->
# stop daemon -> retag :prod -> restart web (blocks until healthy) -> start daemon.
# On an unhealthy web the previous image is re-promoted and the script fails.
#
# Safety: this script only ever touches the zebra-web / zebra-daemon user units.
# It never restarts the GitLab runner, sshd, cloudflared or host networking.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
IMAGE=localhost/zebra-web
CONF_DIR="$HOME/.config/zebra"
ENV_FILE="$CONF_DIR/prod.env"
SITE_FILE="$CONF_DIR/site.env"       # hand-maintained, non-secret (WebAuthn origin, budget...)
SECRET_KEY_FILE="$CONF_DIR/django_secret_key"
QUADLET_DIR="$HOME/.config/containers/systemd"
KEEP_IMAGES="${KEEP_IMAGES:-5}"
# Secrets copied from GitLab CI variables into prod.env when present in the environment.
SECRET_VARS=(ORACLE_DSN ORACLE_USERNAME ORACLE_PASSWORD ANTHROPIC_API_KEY KAGI_API_KEY)

# CI jobs run via `su` without a login session; point systemctl at opc's user manager.
export XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-/run/user/$(id -u)}"
export DBUS_SESSION_BUS_ADDRESS="${DBUS_SESSION_BUS_ADDRESS:-unix:path=$XDG_RUNTIME_DIR/bus}"
sctl() { systemctl --user "$@"; }
log() { printf '== %s\n' "$*"; }

write_env_file() {
  install -d -m 700 "$CONF_DIR"
  if [ -z "${ORACLE_DSN:-}" ]; then
    [ -f "$ENV_FILE" ] || { echo "ERROR: no ORACLE_DSN in env and no $ENV_FILE" >&2; exit 1; }
    log "No CI secrets in environment — keeping existing $ENV_FILE"
    return
  fi
  if [ ! -s "$SECRET_KEY_FILE" ]; then
    (umask 077; openssl rand -base64 48 | tr -d '\n' > "$SECRET_KEY_FILE")
  fi
  local tmp
  tmp="$(mktemp "$CONF_DIR/.prod.env.XXXXXX")"
  chmod 600 "$tmp"
  {
    echo "# Generated by scripts/deploy-podman.sh — do not edit; edit site.env instead."
    # podman --env-file takes values literally: no quotes, no shell expansion.
    for v in "${SECRET_VARS[@]}"; do
      [ -n "${!v:-}" ] && printf '%s=%s\n' "$v" "${!v}"
    done
    printf 'DJANGO_SECRET_KEY=%s\n' "$(cat "$SECRET_KEY_FILE")"
    [ -f "$SITE_FILE" ] && grep -vE '^\s*(#|$)' "$SITE_FILE"
  } > "$tmp"
  mv "$tmp" "$ENV_FILE"
  log "Wrote $ENV_FILE"
}

install_units() {
  install -d "$QUADLET_DIR"
  install -m 644 "$REPO_ROOT"/deploy/podman/quadlet/*.container "$QUADLET_DIR/"
  sctl daemon-reload
}

promote() {  # promote <image-ref>: swap :prod to <image-ref>, never overlapping daemons
  local ref=$1
  log "Stopping daemon"
  sctl stop zebra-daemon.service || true
  podman tag "$ref" "$IMAGE:prod"
  log "Restarting web (waits for healthy)"
  sctl restart zebra-web.service
}

health() { curl -sf --max-time 5 http://127.0.0.1:8000/api/health/ >/dev/null; }

rollback_to() {
  local prev=$1
  log "ROLLBACK to $prev"
  promote "$prev" && sctl start zebra-daemon.service
}

provision_smoke_user() {
  [ -n "${SMOKE_PASSWORD:-}" ] || return 0
  podman exec -e SMOKE_PASSWORD zebra-web python zebra-agent-web/manage.py shell -c \
    "import os; from django.contrib.auth.models import User;
u,_=User.objects.get_or_create(username='smoke');
u.set_password(os.environ['SMOKE_PASSWORD']); u.save(); print('Smoke user ready')"
}

prune_images() {
  # Keep the newest $KEEP_IMAGES tagged builds (plus whatever :prod points at).
  podman images "$IMAGE" --format '{{.Tag}} {{.CreatedAt}}' \
    | grep -vE '^(prod|previous|<none>) ' | sort -k2 -r | awk '{print $1}' \
    | tail -n +"$((KEEP_IMAGES + 1))" \
    | while read -r t; do podman rmi "$IMAGE:$t" >/dev/null 2>&1 || true; done
  podman image prune -f >/dev/null
}

main() {
  local prev=""
  podman image exists "$IMAGE:prod" && prev="$(podman image inspect "$IMAGE:prod" --format '{{.Id}}')"

  if [ "${1:-}" = "--rollback" ]; then
    podman image exists "$IMAGE:previous" || { echo "ERROR: no $IMAGE:previous" >&2; exit 1; }
    install_units
    rollback_to "$IMAGE:previous"
    exit 0
  fi

  local tag=${1:?usage: deploy-podman.sh <tag> | --rollback}
  write_env_file

  log "Building $IMAGE:$tag"
  podman build -t "$IMAGE:$tag" "$REPO_ROOT"

  install_units
  [ -n "$prev" ] && podman tag "$prev" "$IMAGE:previous"

  if promote "$IMAGE:$tag" && health; then
    sctl start zebra-daemon.service  # boot-time start comes from the units' [Install]
    provision_smoke_user
    prune_images
    log "Deployed $IMAGE:$tag"
    podman ps --filter name=zebra- --format '{{.Names}}\t{{.Image}}\t{{.Status}}'
  else
    sctl status zebra-web.service --no-pager -n 30 || true
    [ -n "$prev" ] && rollback_to "$prev"
    echo "ERROR: deploy of $tag failed health check" >&2
    exit 1
  fi
}

main "$@"
